version: 0.2


phases:
  build:
    commands:
      - echo Build started...
      - mvn clean install
  post_build:
    commands:
      - echo Build completed...
artifacts:
  files:
   - target/order-service.jar

